theme = "hyde" 
baseURL = "https://suvam.me/MLNotes/category/" # Please enter your githubpage's url here 
languageCode = "en-us" 
title = "ML Notes" 
[Menus] 
main = [ 
{Name = "Github", URL = "https://github.com/YedMavus/"}, 
{Name = "LinkedIn", URL = "https://www.linkedin.com/in/suvam-dey/"}, 
{Name = "PageHome", URL = "https://yedmavus.github.io/MLNotes/category/"} ] 
[params] 
description =   "Machine Learning Notes Based on Andrew Ng's ML lectures and NPTEL Lectures at IIT-Kgp | Course instructor Prof Ng and Prof Sudeshna Saha | Notes taken by Suvam Dey" theme = "hyde" layoutReverse = true themeColor = "theme-base-0d" disqusShortname = "spf13"
