baseURL = "https://yedmavus.github.io/MLNotes/" # Please enter your githubpage's url here
languageCode = "en-us"
title = "Machine Learning Notes"
theme = "hyde"


[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/YedMavus/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/suvam-dey/"}
  ]

[params]
  description =   "
  Machine Learning Notes Based on NPTEL Lectures at IIT-Kgp  
  Course instructor Prof Sudeshna Saha 
  Notes taken by Suvam Dey
 "

  
  
