baseURL = "https://yedmavus.github.io/latexhugo/" # Please enter your githubpage's url here
languageCode = "en-us"
title = "Machine Learning Notes Based on NPTEL Lectures at IIT-Kgp"
theme = "hyde"


[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/YedMavus/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/suvam-dey/"}
  ]

[params]
  description = """Course Instructor Prof. Sudeshna Saha /
  All notes taken by Suvam Dey"""
